### ISSUE TITLE
The spark driver has stopped unexpectedly and is restarting.

### ISSUE THREAD

**Issue by cashish0106** [procter-gamble-oss/octopufs#8]
Hey Jacek,

Thank you for the utility, it seems it has many features required day to day operation. I am trying to use it to get lake size however it's keep crashing driver and doesnt return the result. I am using databricks and in standard error - I see messages like "OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0" and Out of memory error.

I am using jar - Octopufs_spark3_0_1_scala_2_12.jar 
ADB - 7.3 LTS (Includes Apache Spark 3.0.1, Scala 2.12)

Any pointer or help to fix it?

**Comment by JacekTokar** [comment]
Hey,

The issue you faced is probably related to the way how I implemented recursion for listing elements on the file system. I have fixed it in https://github.com/procter-gamble-tech/octopufs/releases/tag/1.1.1 . Check this out and let me know if it works - it works on the biggest storage account and smallest driver I have access to at the moment.

There are few other functions (like settings acls) which have now similar issue - I will fix the remaining ones soon (I hope ;) )

Let me know if the fix helps

Jacek

**Comment by cashish0106** [comment]
Thank you For quick reply and getting it fixed. let me try it out and I will update you

**Comment by cashish0106** [comment]
This time driver is not crashing but keep getting out of memory error
![image](https://user-images.githubusercontent.com/34109963/115095209-45ba6c00-9ed5-11eb-961d-94107ef77915.png)

**Comment by JacekTokar** [comment]
Interesting... what kind of driver do you use and how many files (approximately) you may have on your storage account? If you run it just on one subfolder, does it also crash?

**Comment by cashish0106** [comment]
I have tried with 4 cores/14GB RAM and  8 cores 28 GB RAM. So far if folder size is around 32 TB then it is able to get the result. Overall storage size is 1 PB but I am trying to execute it for each container that has around 60-90 TB with ~10 million files.

**Comment by JacekTokar** [comment]
I was able to replicate the issue. Apparently you run out of memory. Try using bigger driver for that (with more memory), because this function is loading information about every file and folder into memory before doing summariation. This is because after function is done, it returns the collection which enables you to "browse" through directory tree and check the sizes of all nodes. This was done this way because you pay for every request to storage account (a little, but still). 
I guess I could prepare another function which would summarize all results to totals. This should work even on smallest driver, but it would just return size for the folder you are requesting size of and there would be no possibility to drill-down the directory tree without running all the request to SA again. Would you find this helpful?

**Comment by cashish0106** [comment]
yes, this is helpful details. Also its a good thought to have extra function to provide Summary details. I will try with bigger driver and update.

**Comment by JacekTokar** [comment]
I have updated the code a bit to reduce memory consumption. It may not help in your particular case (because it still needs some memory to run :) ).

Please let me know how you find the new release and if the issue can be closed.

**Comment by cashish0106** [comment]
Sure, I couldn't get time to test it earlier. Will use latest code and try.

**Comment by cashish0106** [comment]
Thank you so much for fixing the issue, I am able to access it and this can be closed. 

Also there is a suggestion, currently getSize errors out if folder/file is getting renamed or update during the operation. Instead there can be a  parameter "Error Action" while calling the method and depending on inputs - it can either error out or continue to get sizes of remaining folders.

**Comment by JacekTokar** [comment]
Well, I am not sure if this is good idea, because you would be getting incorrect results if you ignore the error. Please note that running getSize requires files/folders listing from storage account and every such request cost a bot of money, thus I would suggest running it once in a while when you know that there is no ETL happening on the storage (it may be easier to say then do, though :) )

**Comment by cashish0106** [comment]
It's next to impossible to execute this command when continuous transactions are in progress in prod environment. On few occasions we just need to track daily growth and identify if there are any unexpected amount of data added or deleted. 

Anyway that was just a suggestion but thank you for helping and closing the main concern.
